name: Swift

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Build and Run tests
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
